# Wrangler Configuration for Nahan (نهان) IoT Telemetry Gateway Node
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "nahan"
main = "worker.js_"
compatibility_date = "2026-01-01"

# Automatically run the local dev server on a predictable port
[dev]
port = 8787

# D1 Database Configuration for state & config persistence
[[d1_databases]]
binding = "IOT_DB"
database_name = "sadegh"
database_id = "16c7e992-45ad-4964-a88f-123b4af66932"

# Environment Variables & Secrets (Optional)
# If you prefer to bind your Relay IP as an environment variable instead of using the panel settings:
# [vars]
# RELAY_IP = "pro.xy.ip.cmliussss.net"
